# conda env create -f environment.yml && conda activate project_name
# conda env update -f environment.yml --prune
name: project_name
dependencies:
  - python>=3.10
  - pip
  # use requirements.txt to install packages from PyPI
  - pip:
    - -r requirements.txt
  